# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5f27359bc1901ac6d51a8d94caca54c4779a1459313d485d96dfa3eda414e147105e29f1de31de8a9c9b3cabc77c43bc0704dd8ea4df004e0af8af0eb369cfb

test:
  secret_key_base: 3c5d0b3eb32dd0f4bdaad4052b5b6b9650893c672086575564f4054861b8c92151b09d9fb7c8edaee7ea84d28c2ac146e40d20ddd6ecc25fac25511dba3ce787

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
